input {
  file {
    path => "/path/to/ufw.log.txt"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => {
      "message" => "%{SYSLOGTIMESTAMP:datetime} %{HOSTNAME:hostname} kernel: \[UFW %{WORD:action}\] IN=%{DATA:int_in} OUT=%{DATA:int_out}(?: MAC=%{DATA:macaddr})? SRC=%{IP:srcip} DST=%{IP:dstip} LEN=%{INT:bytes} %{GREEDYDATA:ufw_opts} PROTO=%{WORD:protocol}(?: SPT=%{NUMBER:srcport})?(?: DPT=%{NUMBER:dstport})?"
    }
  }

  mutate {
    add_field => {
      "datetime_with_year" => "2024 %{datetime}"
    }
  }

  date {
    match => [
      "datetime_with_year",
      "yyyy MMM dd HH:mm:ss"
    ]
    timezone => "UTC"
    target => "@timestamp"
  }

  mutate {
    remove_field => [
      "message",
      "datetime",
      "datetime_with_year",
      "ufw_opts",
      "int_in",
      "int_out",
      "macaddr"
    ]
  }
}

output {
  elasticsearch {
    hosts => ["https://ELASTICSEARCH_HOST:9200"]
    ssl_enabled => true
    ssl_certificate_authorities => [
      "/etc/logstash/certs/http_ca.crt"
    ]
    api_key => "${ELASTIC_API_KEY}"
    index => "firewall"
  }
}